=== Azure/iot-operations-sdks/doc/dev/proto/ProtoDocument.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="UndocumentedType">
    <xs:attribute name="item" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ObjectPropertyColumnType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="field" type="xs:string" use="required" />
    <xs:attribute name="conditionOn" type="xs:string" />
    <xs:attribute name="true" type="xs:string" />
    <xs:attribute name="false" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ObjectPropertyTableType">
    <xs:sequence>
      <xs:element name="Column" type="ObjectPropertyColumnType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="object" type="xs:string" />
    <xs:attribute name="defaults" type="xs:string" />
    <xs:attribute name="consts" type="xs:string" />
    <xs:attribute name="kinds" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ObjectSubtypeColumnType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="field" type="xs:string" use="required" />
    <xs:attribute name="conditionOn" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ObjectSubtypeTableType">
    <xs:sequence>
      <xs:element name="Column" type="ObjectSubtypeColumnType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="object" type="xs:string" />
    <xs:attribute name="discriminator" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="EnumValueColumnType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="field" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="EnumValueTableType">
    <xs:sequence>
      <xs:element name="Column" type="EnumValueColumnType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="object" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="TestCaseColumnType">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="field" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="TestCaseTableType">
    <xs:sequence>
      <xs:element name="Column" type="TestCaseColumnType" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="suite" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="ItemizationType">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Item" type="xs:string" />
        <xs:element name="Indent" type="ItemizationType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="baseExampleType">
    <xs:attribute name="minChildren" type="xs:integer" />
    <xs:attribute name="maxWidth" type="xs:integer" />
    <xs:attribute name="minLines" type="xs:integer" />
    <xs:attribute name="maxLines" type="xs:integer" />
  </xs:complexType>

  <xs:complexType name="ExampleDefaultsType">
    <xs:complexContent>
      <xs:extension base="baseExampleType">
        <xs:attribute name="targetLines" type="xs:integer" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="IncludeExcludeType">
    <xs:attribute name="key" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="ExampleType" mixed="true">
    <xs:complexContent>
      <xs:extension base="baseExampleType">
        <xs:sequence>
          <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Include" type="IncludeExcludeType" />
            <xs:element name="Exclude" type="IncludeExcludeType" />
          </xs:choice>
        </xs:sequence>
        <xs:attribute name="suite" type="xs:string" />
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute name="targetLines" type="xs:integer" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="CodeBlockType" mixed="true">
    <xs:attribute name="language" type="xs:string" />
    <xs:attribute name="source" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="HeaderType" mixed="true">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Undocumented" type="UndocumentedType" />
        <xs:element name="ObjectPropertyTable" type="ObjectPropertyTableType" />
        <xs:element name="ExampleDefaults" type="ExampleDefaultsType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="HeadingType" mixed="true">
  </xs:complexType>

  <xs:group name="sectionContentGroup">
    <xs:choice>
      <xs:element name="Subsubheading" type="HeadingType" />
      <xs:element name="Paragraph" type="xs:string" />
      <xs:element name="Itemization" type="ItemizationType" />
      <xs:element name="ObjectPropertyTable" type="ObjectPropertyTableType" />
      <xs:element name="ObjectSubtypeTable" type="ObjectSubtypeTableType" />
      <xs:element name="EnumValueTable" type="EnumValueTableType" />
      <xs:element name="TestCaseTable" type="TestCaseTableType" />
      <xs:element name="Example" type="ExampleType" />
      <xs:element name="CodeBlock" type="CodeBlockType" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="SubsectionType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="sectionContentGroup" />
    </xs:choice>
    <xs:attribute name="item" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="SectionType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="sectionContentGroup" />
      <xs:element name="Heading" type="HeadingType" />
      <xs:element name="Subheading" type="HeadingType" />
      <xs:element name="Subsection" type="SubsectionType" />
    </xs:choice>
    <xs:attribute name="suite" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="BodyType">
    <xs:sequence>
      <xs:element name="Title" type="xs:string" minOccurs="0" />
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="Heading" type="HeadingType" />
        <xs:element name="Section" type="SectionType" />
        <xs:element name="Paragraph" type="xs:string" />
        <xs:element name="Itemization" type="ItemizationType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DocumentType">
    <xs:sequence>
      <xs:element name="Header" type="HeaderType" />
      <xs:element name="Body" type="BodyType" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="Document" type="DocumentType" />

</xs:schema>

=== Azure/iot-operations-sdks/doc/dev/proto/MetlCasesProto.xml
<?xml version="1.0" encoding="utf-8" ?>
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProtoDocument.xsd">

  <Header>
  </Header>

  <Body>

    <Title>Testing for RPC Protocol</Title>

    <Section>

      <Paragraph>
        RPC Protocol is based on well-defined sequences of PUB and PUBACK packets to implement a request/response pattern.
      </Paragraph>

      <Paragraph>
        RPC protocol must be tested using normative unit tests that assert the _expected_ behavior of the protocol. This MUST include at the very least:
      </Paragraph>
      <Itemization>
        <Item>Correct MQTT semantic for PUB and PUBACK ordering: PUBs have to be re-trasmitted and ACKed in the same order they have been sent and observed by the participating clients. See [section 4.6 Message Ordering](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901240) in MQTT5 specification.</Item>
        <Item>Correct de-duplication of requests.</Item>
        <Item>Correct execution of [_idempotent_](http://link_to_idempotent) and [_non-idempotent_](http://link_to_non_idempotent) methods.</Item>
        <Item>Correct lifetime for cached responses.</Item>
        <Item>Correct handling of orphan requests in presence terminal failures of a client or server using [_message_expiry_](http://link_to_message_expiry) at broker side.</Item>
      </Itemization>

      <Paragraph>
        Unit tests must account for at least the following occurrences:
      </Paragraph>
      <Itemization>
        <Item>PUB packet loss.</Item>
        <Item>PUBACK packet loss.</Item>
        <Item>Duplicate requests and/or responses.</Item>
        <Item>Disconnection and re-connection (both for sender and receiver), both due to client failure and/or client being disconnected by the broker (e.g., on account of backpressure).</Item>
        <Item>Failure and sub-sequent re-connection, both on invoker and executor side.</Item>
        <Item>Serving requests inside and outside the [_timeout_](http://link_to_timeout) window indicated by request invokation, both for [_idempotent_](http://link_to_idempotent) and [_non-idempotent_](http://link_to_non_idempotent) methods.</Item>
      </Itemization>

      <Paragraph>
        Unit tests MUST be exhaustive, and therefore MUST neither assume correct behavior of MQTT client nor assume correct behavior of protocol stack in SDK and broker.
        See below for categorized tests.
      </Paragraph>

    </Section>

    <Section suite="CommandExecutor">
      <Heading>CommandExecutor test cases</Heading>

      <TestCaseTable>
        <Column name="Normative statement" field="condition" />
        <Column name="Expected behavior" field="expect"/>
      </TestCaseTable>

    </Section>

    <Section suite="CommandInvoker">
      <Heading>CommandInvoker test cases</Heading>

      <TestCaseTable>
        <Column name="Normative statement" field="condition" />
        <Column name="Expected behavior" field="expect"/>
      </TestCaseTable>

    </Section>

  </Body>

</Document>
